name: Android SDK CI
on:
  push:
    branches: [ master , sdk-tests ]
  pull_request:
    branches: [ master , sdk-tests ]
jobs:
  build-with-upload-artifact:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: run tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            script: ./gradlew connectedCheck
      - name: Build and Test with Gradle
        run: ./gradlew test connectedAndroidTest
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test