name: Android SDK CI
on: [push, pull_request]

env.ANDROID_HOME: '/home/ubuntu/android'

jobs:
  unit-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-33

      - name: Create AVD and Generate Snapshot for Caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 33
          arch: x86_64
          target: playstore
          emulator-build: 9322596 #31.3.14.0 It can be get by running -> ./emulator -version
          force-avd-creation: false
          cores: 3
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - run: ffmpeg -re -i ./webrtc-android-sample-app/src/androidTest/resources/test.flv -codec copy -f flv rtmp://test.antmedia.io/LiveApp/stream556677i4d &

      - name: Run Tests and Generate Report
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 33
          arch: x86_64
          target: playstore
          emulator-build: 9322596 #31.3.14.0 It can be get by running -> ./emulator -version
          force-avd-creation: false
          disable-animations: true
          cores: 3
          emulator-options: -no-snapshot-save -gpu swiftshader_indirect -no-window -noaudio -no-boot-anim
          script: ./gradlew jacocoTestReport; EXIT_CODE=$?; /Users/runner/Library/Android/sdk/platform-tools/adb logcat -d > webrtc-android-sample-app/build/logcat.txt; exit $EXIT_CODE

      - name: Archive Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: |
            webrtc-android-sample-app/build/reports/tests/testDebugUnitTest/
            webrtc-android-sample-app/build/reports/jacoco/jacocoTestReport/
            webrtc-android-sample-app/build/reports/androidTests/
            webrtc-android-framework/build/reports/tests/testDebugUnitTest/
            webrtc-android-framework/build/reports/jacoco/jacocoTestReport/
            webrtc-android-framework/build/reports/androidTests/
            webrtc-android-sample-app/build/logcat.txt
            webrtc-android-sample-app/build/screen.png
      - name: Upload Test Report to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          files: webrtc-android-framework/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,webrtc-android-sample-app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          fail_ci_if_error: true

