name: Android SDK CI
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Run tests and Generate Report
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 29
          script: ./gradlew jacocoTestReport
      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: |
            webrtc-android-sample-app/build/reports/tests/testDebugUnitTest/
            webrtc-android-framework/build/reports/tests/testDebugUnitTest/
      - name: Upload Test Report to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          files: webrtc-android-sample-app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,webrtc-android-framework/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

