name: Android SDK CI
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build and Test with Gradle
        run: ./gradlew test
      - name: Assemble
        run: ./gradlew assemble
      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: |
            webrtc-android-sample-app/build/reports/tests/testDebugUnitTest/
            webrtc-android-framework/build/reports/tests/testDebugUnitTest/